version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.3
        environment:
          BUNDLE_PATH: vendor/bundle
    steps:
      - checkout

      - restore_cache:
          keys:
            - crawler-{{ checksum "Gemfile.lock" }}
            - crawler-

      - run:
          name: install dependencies
          command: bundle install
      
      - save_cache:
          key: crawler-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      
      - run:
          name: run tests
          command: bundle exec rspec